openapi: '3.0.0'
info:
  version: 1.0.0
  title: 'dev-portfolio API'
  description: 'dev-portfolio API'
servers:
  - url: http://localhost:3000/
paths:
  /api/header:
    get:
      response:
        '200':
          descriptoin: 'OK'
          content:
            application/json: "content type"
              schema:
                type: object
                properties:
                  visitorcount:
                    type: number